### PR TITLE
MVP Azure Pipelines

### PR DESCRIPTION
**Pull request by alexanderjervis**
- CI/CD azure pipelines setup
  - Maven build and testing
  - static analysis included
  - dockerizing images for containers
  - deployment to kubernetes clusters using manifests
  - templating and parameterization

### CODE REVIEW

**Review by sophiagavrila — APPROVED** [review]

**Review by MDarmawan — APPROVED** [review]
Progress!

**Review by SWHarrison — APPROVED** [review]

**Review by FBThornton — APPROVED** [review]

**Review by m-james-butler — APPROVED** [review]
Looks good to me.

**Comment by MDarmawan** [comment]
Gonna wait for our trainer @escalonn to approve before we merge.

**Review by escalonn — APPROVED** [review]
https://github.com/1058-Sophia-Gavrila-Forge/Portfolio-Frontend/pull/16#pullrequestreview-717221875

**Pull request merged**
