### PR TITLE
Hotfix: Fixing acr misnomer

### PR DESCRIPTION
**Pull request by alexanderjervis**
- Fix azure repository from using incorrect frontend name to backend.
- Added changes to manifest file for acr integration.

### CODE REVIEW

**Review by escalonn — APPROVED** [review]
if this is a hotfix, why is it bringing in unmerged commit history from 4 days ago? the resulting diff looks fine but that's definitely an anomaly.

**Comment by MDarmawan** [comment]
> if this is a hotfix, why is it bringing in unmerged commit history from 4 days ago? the resulting diff looks fine but that's definitely an anomaly.

So, I think it's probably because I squash merged the previous PR, and alex is keeping his work in the same azure-pipelines branch. I figured squash merges would simplify the commit history for the `dev` branch, but maybe that's not what squash merges are for?

**Comment by escalonn** [comment]
@MDarmawan 😑 why is this PR trying to deploy to the cluster

**Comment by escalonn** [comment]
that makes sense. yeah don't re-use old branches with unmerged commits in the future

**Comment by MDarmawan** [comment]
> @MDarmawan 😑 why is this PR trying to deploy to the cluster

So, the defaults for the parameters will avoid deploying to the real clusters, but since we're testing the imagePull secrets, we did a manual run with non-default parameters to deploy to alex's test cluster, and I think GitHub picked up on that manual run.

**Comment by escalonn** [comment]
ok

**Review by MDarmawan — APPROVED** [review]
Looks good to me.

**Pull request merged**
